import { HttpClient } from '../core/httpClient.js';
import { APSetupAPI } from '../api/APSetupAPI.js';
import { ARSetupAPI } from '../api/ARSetupAPI.js';
import { ActivityAPI } from '../api/ActivityAPI.js';
import { ActivityCodeAPI } from '../api/ActivityCodeAPI.js';
import { ActivityCodeHotkeyAPI } from '../api/ActivityCodeHotkeyAPI.js';
import { ActivityCodeInventoryItemTypeAPI } from '../api/ActivityCodeInventoryItemTypeAPI.js';
import { ActivityCodePLQMappingAPI } from '../api/ActivityCodePLQMappingAPI.js';
import { ActivityCodeUpstreamDependenciesAPI } from '../api/ActivityCodeUpstreamDependenciesAPI.js';
import { ActivityRateAPI } from '../api/ActivityRateAPI.js';
import { ActivityRateMarkupAPI } from '../api/ActivityRateMarkupAPI.js';
import { ActivityTypeAPI } from '../api/ActivityTypeAPI.js';
import { AddressFormatAPI } from '../api/AddressFormatAPI.js';
import { AllowanceExpressionAPI } from '../api/AllowanceExpressionAPI.js';
import { AlternatePrintMethodAPI } from '../api/AlternatePrintMethodAPI.js';
import { AlternatePrintMethodContentAPI } from '../api/AlternatePrintMethodContentAPI.js';
import { ApprovalGroupAPI } from '../api/ApprovalGroupAPI.js';
import { AssetClassAPI } from '../api/AssetClassAPI.js';
import { AssetDepBatchAPI } from '../api/AssetDepBatchAPI.js';
import { AssetDepLineAPI } from '../api/AssetDepLineAPI.js';
import { AssetPostingGroupAPI } from '../api/AssetPostingGroupAPI.js';
import { AssetTransactionAPI } from '../api/AssetTransactionAPI.js';
import { AssetTransactionBatchAPI } from '../api/AssetTransactionBatchAPI.js';
import { AttachmentCategoryAPI } from '../api/AttachmentCategoryAPI.js';
import { AttachmentRuleAPI } from '../api/AttachmentRuleAPI.js';
import { AttachmentSetupAPI } from '../api/AttachmentSetupAPI.js';
import { AutoBillAPI } from '../api/AutoBillAPI.js';
import { AutoBillLineAPI } from '../api/AutoBillLineAPI.js';
import { AutoInvoiceAPI } from '../api/AutoInvoiceAPI.js';
import { AutoInvoiceLineAPI } from '../api/AutoInvoiceLineAPI.js';
import { BankAccountAPI } from '../api/BankAccountAPI.js';
import { BankAccountLineAPI } from '../api/BankAccountLineAPI.js';
import { BankStatementAPI } from '../api/BankStatementAPI.js';
import { BillAPI } from '../api/BillAPI.js';
import { BillBatchAPI } from '../api/BillBatchAPI.js';
import { BillCheckAPI } from '../api/BillCheckAPI.js';
import { BillLineAPI } from '../api/BillLineAPI.js';
import { BillOfLadingAPI } from '../api/BillOfLadingAPI.js';
import { BillPaymentAPI } from '../api/BillPaymentAPI.js';
import { BillPaymentBatchAPI } from '../api/BillPaymentBatchAPI.js';
import { BillStatusAPI } from '../api/BillStatusAPI.js';
import { BinderAPI } from '../api/BinderAPI.js';
import { BinderSpeedAPI } from '../api/BinderSpeedAPI.js';
import { BindingMethodAPI } from '../api/BindingMethodAPI.js';
import { BindingMethodFinishingOpAPI } from '../api/BindingMethodFinishingOpAPI.js';
import { CRMSetupAPI } from '../api/CRMSetupAPI.js';
import { CRMStatusAPI } from '../api/CRMStatusAPI.js';
import { CRMUserAPI } from '../api/CRMUserAPI.js';
import { CSRAPI } from '../api/CSRAPI.js';
import { CampaignAPI } from '../api/CampaignAPI.js';
import { CampaignNoteAPI } from '../api/CampaignNoteAPI.js';
import { CampaignTypeAPI } from '../api/CampaignTypeAPI.js';
import { CartonAPI } from '../api/CartonAPI.js';
import { CartonContentAPI } from '../api/CartonContentAPI.js';
import { CertificationAuthorityAPI } from '../api/CertificationAuthorityAPI.js';
import { CertificationLevelAPI } from '../api/CertificationLevelAPI.js';
import { CertificationProductClassificationAPI } from '../api/CertificationProductClassificationAPI.js';
import { CertificationTrainingAPI } from '../api/CertificationTrainingAPI.js';
import { ChangeOrderAPI } from '../api/ChangeOrderAPI.js';
import { ChangeOrderLineAPI } from '../api/ChangeOrderLineAPI.js';
import { ChangeOrderTypeAPI } from '../api/ChangeOrderTypeAPI.js';
import { ChargeBackAccountAPI } from '../api/ChargeBackAccountAPI.js';
import { ComboJobAPI } from '../api/ComboJobAPI.js';
import { CompanyAPI } from '../api/CompanyAPI.js';
import { ComponentTypeAPI } from '../api/ComponentTypeAPI.js';
import { ContactAPI } from '../api/ContactAPI.js';
import { ContactNoteAPI } from '../api/ContactNoteAPI.js';
import { ContentFileAPI } from '../api/ContentFileAPI.js';
import { ContentFileCategoryAPI } from '../api/ContentFileCategoryAPI.js';
import { ContentFileContourAPI } from '../api/ContentFileContourAPI.js';
import { CostCategoryAPI } from '../api/CostCategoryAPI.js';
import { CostCenterAPI } from '../api/CostCenterAPI.js';
import { CostCenterTypeAPI } from '../api/CostCenterTypeAPI.js';
import { CountryAPI } from '../api/CountryAPI.js';
import { CountryGroupAPI } from '../api/CountryGroupAPI.js';
import { CountryGroupMemberAPI } from '../api/CountryGroupMemberAPI.js';
import { CurrencyAPI } from '../api/CurrencyAPI.js';
import { CurrencyExchangeRateAPI } from '../api/CurrencyExchangeRateAPI.js';
import { CustomerAPI } from '../api/CustomerAPI.js';
import { CustomerCalculateAPI } from '../api/CustomerCalculateAPI.js';
import { CustomerCommissionDistributionAPI } from '../api/CustomerCommissionDistributionAPI.js';
import { CustomerGroupAPI } from '../api/CustomerGroupAPI.js';
import { CustomerGroupDiscountAPI } from '../api/CustomerGroupDiscountAPI.js';
import { CustomerNoteAPI } from '../api/CustomerNoteAPI.js';
import { CustomerPaymentMethodAPI } from '../api/CustomerPaymentMethodAPI.js';
import { CustomerShoppingCartExtraAPI } from '../api/CustomerShoppingCartExtraAPI.js';
import { CustomerStatusAPI } from '../api/CustomerStatusAPI.js';
import { CustomerTypeAPI } from '../api/CustomerTypeAPI.js';
import { CutterAPI } from '../api/CutterAPI.js';
import { CutterAlignmentMarkGroupAPI } from '../api/CutterAlignmentMarkGroupAPI.js';
import { CycleCountAPI } from '../api/CycleCountAPI.js';
import { DSFEntityAPI } from '../api/DSFEntityAPI.js';
import { DSFMediaSizeAPI } from '../api/DSFMediaSizeAPI.js';
import { DSFOrderStatusAPI } from '../api/DSFOrderStatusAPI.js';
import { DataCollectionSetupAPI } from '../api/DataCollectionSetupAPI.js';
import { DefaultEstimateFinishingOpAPI } from '../api/DefaultEstimateFinishingOpAPI.js';
import { DefaultEstimateOptionAPI } from '../api/DefaultEstimateOptionAPI.js';
import { DepartmentAPI } from '../api/DepartmentAPI.js';
import { DepreciationMethodAPI } from '../api/DepreciationMethodAPI.js';
import { DetailUOMAPI } from '../api/DetailUOMAPI.js';
import { DeviceCapabilityAPI } from '../api/DeviceCapabilityAPI.js';
import { DigitalWorkflowSetupAPI } from '../api/DigitalWorkflowSetupAPI.js';
import { DisAllowedAutoChangeableToJobStatusAPI } from '../api/DisAllowedAutoChangeableToJobStatusAPI.js';
import { DistributionAPI } from '../api/DistributionAPI.js';
import { DunningLetterAPI } from '../api/DunningLetterAPI.js';
import { EPaceStationSetupAPI } from '../api/EPaceStationSetupAPI.js';
import { EmailTemplateAPI } from '../api/EmailTemplateAPI.js';
import { EmailTemplateCategoryAPI } from '../api/EmailTemplateCategoryAPI.js';
import { EmployeeAPI } from '../api/EmployeeAPI.js';
import { EmployeeCountTypeAPI } from '../api/EmployeeCountTypeAPI.js';
import { EmployeeHotkeyAPI } from '../api/EmployeeHotkeyAPI.js';
import { EmployeeNoteAPI } from '../api/EmployeeNoteAPI.js';
import { EmployeePayrollDeductionAPI } from '../api/EmployeePayrollDeductionAPI.js';
import { EmployeeStatusAPI } from '../api/EmployeeStatusAPI.js';
import { EmployeeTimeAPI } from '../api/EmployeeTimeAPI.js';
import { EmployeeTimeSessionAPI } from '../api/EmployeeTimeSessionAPI.js';
import { EserviceSetupAPI } from '../api/EserviceSetupAPI.js';
import { EstimateAPI } from '../api/EstimateAPI.js';
import { EstimateActivityAPI } from '../api/EstimateActivityAPI.js';
import { EstimateCalcMessageAPI } from '../api/EstimateCalcMessageAPI.js';
import { EstimateCartonAPI } from '../api/EstimateCartonAPI.js';
import { EstimateCartonContentAPI } from '../api/EstimateCartonContentAPI.js';
import { EstimateComponentAPI } from '../api/EstimateComponentAPI.js';
import { EstimateCompositeProductAPI } from '../api/EstimateCompositeProductAPI.js';
import { EstimateCompositeProductEntryAPI } from '../api/EstimateCompositeProductEntryAPI.js';
import { EstimateExpressionAPI } from '../api/EstimateExpressionAPI.js';
import { EstimateFinishingOpAPI } from '../api/EstimateFinishingOpAPI.js';
import { EstimateIntentInfoAPI } from '../api/EstimateIntentInfoAPI.js';
import { EstimateItemAPI } from '../api/EstimateItemAPI.js';
import { EstimateLayoutAPI } from '../api/EstimateLayoutAPI.js';
import { EstimateLayoutContentAPI } from '../api/EstimateLayoutContentAPI.js';
import { EstimateMailAPI } from '../api/EstimateMailAPI.js';
import { EstimateMaterialAPI } from '../api/EstimateMaterialAPI.js';
import { EstimateNoteAPI } from '../api/EstimateNoteAPI.js';
import { EstimateOptionAPI } from '../api/EstimateOptionAPI.js';
import { EstimateOutsidePurchAPI } from '../api/EstimateOutsidePurchAPI.js';
import { EstimatePaperAPI } from '../api/EstimatePaperAPI.js';
import { EstimatePartAPI } from '../api/EstimatePartAPI.js';
import { EstimatePartContentFileAPI } from '../api/EstimatePartContentFileAPI.js';
import { EstimatePartImpositionAllowanceAPI } from '../api/EstimatePartImpositionAllowanceAPI.js';
import { EstimatePartSizeAllowanceAPI } from '../api/EstimatePartSizeAllowanceAPI.js';
import { EstimatePrepressOpAPI } from '../api/EstimatePrepressOpAPI.js';
import { EstimatePressAPI } from '../api/EstimatePressAPI.js';
import { EstimatePressContentAPI } from '../api/EstimatePressContentAPI.js';
import { EstimatePressEventAPI } from '../api/EstimatePressEventAPI.js';
import { EstimatePressInkAPI } from '../api/EstimatePressInkAPI.js';
import { EstimatePressMixedMediaAPI } from '../api/EstimatePressMixedMediaAPI.js';
import { EstimatePriceSummaryAPI } from '../api/EstimatePriceSummaryAPI.js';
import { EstimateProductAPI } from '../api/EstimateProductAPI.js';
import { EstimateProductCategoryAPI } from '../api/EstimateProductCategoryAPI.js';
import { EstimateProductCategoryJobProductTypeAPI } from '../api/EstimateProductCategoryJobProductTypeAPI.js';
import { EstimateProductPriceSummaryAPI } from '../api/EstimateProductPriceSummaryAPI.js';
import { EstimateQuantityAPI } from '../api/EstimateQuantityAPI.js';
import { EstimateQuantityCommissionDistributionAPI } from '../api/EstimateQuantityCommissionDistributionAPI.js';
import { EstimateQuantityContributionAnalysisAPI } from '../api/EstimateQuantityContributionAnalysisAPI.js';
import { EstimateQuoteLetterAPI } from '../api/EstimateQuoteLetterAPI.js';
import { EstimateQuoteLetterNoteAPI } from '../api/EstimateQuoteLetterNoteAPI.js';
import { EstimateQuoteLetterNotePriceAPI } from '../api/EstimateQuoteLetterNotePriceAPI.js';
import { EstimateRequestAPI } from '../api/EstimateRequestAPI.js';
import { EstimateRequestComponentAPI } from '../api/EstimateRequestComponentAPI.js';
import { EstimateRequestFinishingOpAPI } from '../api/EstimateRequestFinishingOpAPI.js';
import { EstimateRequestItemAPI } from '../api/EstimateRequestItemAPI.js';
import { EstimateRequestMaterialAPI } from '../api/EstimateRequestMaterialAPI.js';
import { EstimateRequestNoteAPI } from '../api/EstimateRequestNoteAPI.js';
import { EstimateRequestOptionAPI } from '../api/EstimateRequestOptionAPI.js';
import { EstimateRequestPartAPI } from '../api/EstimateRequestPartAPI.js';
import { EstimateRequestPartSizeAllowanceAPI } from '../api/EstimateRequestPartSizeAllowanceAPI.js';
import { EstimateRequestPrepressOpAPI } from '../api/EstimateRequestPrepressOpAPI.js';
import { EstimateRequestPressEventAPI } from '../api/EstimateRequestPressEventAPI.js';
import { EstimateRequestProductAPI } from '../api/EstimateRequestProductAPI.js';
import { EstimateRequestSetupAPI } from '../api/EstimateRequestSetupAPI.js';
import { EstimateRequestStatusAPI } from '../api/EstimateRequestStatusAPI.js';
import { EstimateSetupAPI } from '../api/EstimateSetupAPI.js';
import { EstimateShipmentAPI } from '../api/EstimateShipmentAPI.js';
import { EstimateSkidAPI } from '../api/EstimateSkidAPI.js';
import { EstimateStatusAPI } from '../api/EstimateStatusAPI.js';
import { EstimateVariantSetAPI } from '../api/EstimateVariantSetAPI.js';
import { EstimateVariantSetEntryAPI } from '../api/EstimateVariantSetEntryAPI.js';
import { EstimatedPricingPolicyAPI } from '../api/EstimatedPricingPolicyAPI.js';
import { EstimatorAPI } from '../api/EstimatorAPI.js';
import { EventHandlerConditionDefinitionAPI } from '../api/EventHandlerConditionDefinitionAPI.js';
import { EventHandlerDefinitionAPI } from '../api/EventHandlerDefinitionAPI.js';
import { EventHandlerEmailConsequenceDefinitionAPI } from '../api/EventHandlerEmailConsequenceDefinitionAPI.js';
import { EventHandlerEmailRecipientAPI } from '../api/EventHandlerEmailRecipientAPI.js';
import { EventHandlerEmailReportAttachmentAPI } from '../api/EventHandlerEmailReportAttachmentAPI.js';
import { EventHandlerEventDefinitionAPI } from '../api/EventHandlerEventDefinitionAPI.js';
import { EventHandlerExecuteConnectDefinitionAPI } from '../api/EventHandlerExecuteConnectDefinitionAPI.js';
import { EventHandlerNotificationConsequenceDefinitionAPI } from '../api/EventHandlerNotificationConsequenceDefinitionAPI.js';
import { EventHandlerNotificationRecipientAPI } from '../api/EventHandlerNotificationRecipientAPI.js';
import { EventHandlerPrintReportDefinitionAPI } from '../api/EventHandlerPrintReportDefinitionAPI.js';
import { ExpressionAPI } from '../api/ExpressionAPI.js';
import { ExpressionCategoryAPI } from '../api/ExpressionCategoryAPI.js';
import { ExternalBODPrimaryKeyReferenceAPI } from '../api/ExternalBODPrimaryKeyReferenceAPI.js';
import { ExtraStockAPI } from '../api/ExtraStockAPI.js';
import { FASetupAPI } from '../api/FASetupAPI.js';
import { FacebookAccountAPI } from '../api/FacebookAccountAPI.js';
import { FileAttachmentAPI } from '../api/FileAttachmentAPI.js';
import { FileAttachmentMetaAPI } from '../api/FileAttachmentMetaAPI.js';
import { FileTypeAPI } from '../api/FileTypeAPI.js';
import { FinGoodsOrderAPI } from '../api/FinGoodsOrderAPI.js';
import { FinishingMachineTypeAPI } from '../api/FinishingMachineTypeAPI.js';
import { FinishingOperationAPI } from '../api/FinishingOperationAPI.js';
import { FinishingOperationDisplayAttributeAPI } from '../api/FinishingOperationDisplayAttributeAPI.js';
import { FinishingOperationGroupAPI } from '../api/FinishingOperationGroupAPI.js';
import { FinishingOperationMaterialAPI } from '../api/FinishingOperationMaterialAPI.js';
import { FinishingOperationSpeedAPI } from '../api/FinishingOperationSpeedAPI.js';
import { FixedAssetAPI } from '../api/FixedAssetAPI.js';
import { FixedAssetNoteAPI } from '../api/FixedAssetNoteAPI.js';
import { FoldPatternAPI } from '../api/FoldPatternAPI.js';
import { FolderAPI } from '../api/FolderAPI.js';
import { FolderSpeedAPI } from '../api/FolderSpeedAPI.js';
import { FontAPI } from '../api/FontAPI.js';
import { FreightClassificationAPI } from '../api/FreightClassificationAPI.js';
import { FreightLinkUPSEntryAPI } from '../api/FreightLinkUPSEntryAPI.js';
import { FulfillmentSetupAPI } from '../api/FulfillmentSetupAPI.js';
import { GLAccountAPI } from '../api/GLAccountAPI.js';
import { GLAccountBalanceAPI } from '../api/GLAccountBalanceAPI.js';
import { GLAccountBalanceSummaryAPI } from '../api/GLAccountBalanceSummaryAPI.js';
import { GLAccountBudgetAPI } from '../api/GLAccountBudgetAPI.js';
import { GLAccountingPeriodAPI } from '../api/GLAccountingPeriodAPI.js';
import { GLAccountingPeriodSummaryNameAPI } from '../api/GLAccountingPeriodSummaryNameAPI.js';
import { GLBatchAPI } from '../api/GLBatchAPI.js';
import { GLDepartmentAPI } from '../api/GLDepartmentAPI.js';
import { GLDepartmentLocationAPI } from '../api/GLDepartmentLocationAPI.js';
import { GLJournalEntryAPI } from '../api/GLJournalEntryAPI.js';
import { GLJournalEntryAuditAPI } from '../api/GLJournalEntryAuditAPI.js';
import { GLLocationAPI } from '../api/GLLocationAPI.js';
import { GLRegisterNumberAPI } from '../api/GLRegisterNumberAPI.js';
import { GLScheduleAPI } from '../api/GLScheduleAPI.js';
import { GLScheduleLineAPI } from '../api/GLScheduleLineAPI.js';
import { GLSetupAPI } from '../api/GLSetupAPI.js';
import { GLSplitAPI } from '../api/GLSplitAPI.js';
import { GLSummaryNameAPI } from '../api/GLSummaryNameAPI.js';
import { GenericFinishingMachineAPI } from '../api/GenericFinishingMachineAPI.js';
import { GenericFinishingSpeedAPI } from '../api/GenericFinishingSpeedAPI.js';
import { HowToDeDupeAPI } from '../api/HowToDeDupeAPI.js';
import { I18nBundleAPI } from '../api/I18nBundleAPI.js';
import { ImportControlAPI } from '../api/ImportControlAPI.js';
import { ImportElementAPI } from '../api/ImportElementAPI.js';
import { ImportTemplateAPI } from '../api/ImportTemplateAPI.js';
import { ImportTemplateCategoryAPI } from '../api/ImportTemplateCategoryAPI.js';
import { ImportTemplateObjectNodeAPI } from '../api/ImportTemplateObjectNodeAPI.js';
import { ImportTemplateParameterAPI } from '../api/ImportTemplateParameterAPI.js';
import { ImportTemplateXPathVariableAPI } from '../api/ImportTemplateXPathVariableAPI.js';
import { IndexMetaDataAPI } from '../api/IndexMetaDataAPI.js';
import { IndustryTypeAPI } from '../api/IndustryTypeAPI.js';
import { InkAPI } from '../api/InkAPI.js';
import { InkDefaultAPI } from '../api/InkDefaultAPI.js';
import { InkDefaultInkAPI } from '../api/InkDefaultInkAPI.js';
import { InquiryDefinitionAPI } from '../api/InquiryDefinitionAPI.js';
import { InsertTypeAPI } from '../api/InsertTypeAPI.js';
import { InstallationToolAPI } from '../api/InstallationToolAPI.js';
import { InstallationToolCategoryAPI } from '../api/InstallationToolCategoryAPI.js';
import { InstallationToolChecklistAPI } from '../api/InstallationToolChecklistAPI.js';
import { InventoryBatchAPI } from '../api/InventoryBatchAPI.js';
import { InventoryBinAPI } from '../api/InventoryBinAPI.js';
import { InventoryBinQuantityAPI } from '../api/InventoryBinQuantityAPI.js';
import { InventoryConversionAPI } from '../api/InventoryConversionAPI.js';
import { InventoryConversionTargetAPI } from '../api/InventoryConversionTargetAPI.js';
import { InventoryItemAPI } from '../api/InventoryItemAPI.js';
import { InventoryItemCertificationAPI } from '../api/InventoryItemCertificationAPI.js';
import { InventoryItemKitAPI } from '../api/InventoryItemKitAPI.js';
import { InventoryItemManufacturingLocationAPI } from '../api/InventoryItemManufacturingLocationAPI.js';
import { InventoryItemPurchaseUomAPI } from '../api/InventoryItemPurchaseUomAPI.js';
import { InventoryItemTypeAPI } from '../api/InventoryItemTypeAPI.js';
import { InventoryItemVendorAPI } from '../api/InventoryItemVendorAPI.js';
import { InventoryItemVendorCostAPI } from '../api/InventoryItemVendorCostAPI.js';
import { InventoryLineAPI } from '../api/InventoryLineAPI.js';
import { InventoryLocationAPI } from '../api/InventoryLocationAPI.js';
import { InventoryLocationQuantityAPI } from '../api/InventoryLocationQuantityAPI.js';
import { InventorySetupAPI } from '../api/InventorySetupAPI.js';
import { InventoryStatusAPI } from '../api/InventoryStatusAPI.js';
import { InventoryTrnTypeAPI } from '../api/InventoryTrnTypeAPI.js';
import { InvoiceAPI } from '../api/InvoiceAPI.js';
import { InvoiceBatchAPI } from '../api/InvoiceBatchAPI.js';
import { InvoiceBodIDLinkAPI } from '../api/InvoiceBodIDLinkAPI.js';
import { InvoiceCommDistAPI } from '../api/InvoiceCommDistAPI.js';
import { InvoiceExtraAPI } from '../api/InvoiceExtraAPI.js';
import { InvoiceExtraTypeAPI } from '../api/InvoiceExtraTypeAPI.js';
import { InvoiceLineAPI } from '../api/InvoiceLineAPI.js';
import { InvoiceSalesDistAPI } from '../api/InvoiceSalesDistAPI.js';
import { InvoiceSourceAPI } from '../api/InvoiceSourceAPI.js';
import { InvoiceTaxDistAPI } from '../api/InvoiceTaxDistAPI.js';
import { InvoiceTypeAPI } from '../api/InvoiceTypeAPI.js';
import { IssueAPI } from '../api/IssueAPI.js';
import { IssueCommentAPI } from '../api/IssueCommentAPI.js';
import { IssueResolutionAPI } from '../api/IssueResolutionAPI.js';
import { IssueStatusAPI } from '../api/IssueStatusAPI.js';
import { IssueSubTypeAPI } from '../api/IssueSubTypeAPI.js';
import { IssueTypeAPI } from '../api/IssueTypeAPI.js';
import { ItemTemplateAPI } from '../api/ItemTemplateAPI.js';
import { ItemTemplateComboLinkAPI } from '../api/ItemTemplateComboLinkAPI.js';
import { ItemTemplateLineAPI } from '../api/ItemTemplateLineAPI.js';
import { ItemTemplateLineAttributeAPI } from '../api/ItemTemplateLineAttributeAPI.js';
import { ItemTemplateProductTypeAPI } from '../api/ItemTemplateProductTypeAPI.js';
import { ItemTemplateProductTypeItemAPI } from '../api/ItemTemplateProductTypeItemAPI.js';
import { ItemTemplateProductTypeMappingAPI } from '../api/ItemTemplateProductTypeMappingAPI.js';
import { ItemTemplateQuantityAPI } from '../api/ItemTemplateQuantityAPI.js';
import { ItemTemplateSetupAPI } from '../api/ItemTemplateSetupAPI.js';
import { ItemTemplateTypeAPI } from '../api/ItemTemplateTypeAPI.js';
import { JMFReceivedMessageAPI } from '../api/JMFReceivedMessageAPI.js';
import { JMFReceivedMessagePartitionAPI } from '../api/JMFReceivedMessagePartitionAPI.js';
import { JMFReceivedMessageTransactionAPI } from '../api/JMFReceivedMessageTransactionAPI.js';
import { JMFReceivedMessageTransactionPartitionAPI } from '../api/JMFReceivedMessageTransactionPartitionAPI.js';
import { JobAPI } from '../api/JobAPI.js';
import { JobArchiveAPI } from '../api/JobArchiveAPI.js';
import { JobBillingAccountingCodeAPI } from '../api/JobBillingAccountingCodeAPI.js';
import { JobBillingSetupAPI } from '../api/JobBillingSetupAPI.js';
import { JobComponentAPI } from '../api/JobComponentAPI.js';
import { JobContactAPI } from '../api/JobContactAPI.js';
import { JobControlSetupAPI } from '../api/JobControlSetupAPI.js';
import { JobCostAPI } from '../api/JobCostAPI.js';
import { JobCostSetupAPI } from '../api/JobCostSetupAPI.js';
import { JobCostTypeAPI } from '../api/JobCostTypeAPI.js';
import { JobDifficultyAPI } from '../api/JobDifficultyAPI.js';
import { JobDiscountAPI } from '../api/JobDiscountAPI.js';
import { JobMaterialAPI } from '../api/JobMaterialAPI.js';
import { JobNoteAPI } from '../api/JobNoteAPI.js';
import { JobOverAPI } from '../api/JobOverAPI.js';
import { JobPartAPI } from '../api/JobPartAPI.js';
import { JobPartCommissionDistributionAPI } from '../api/JobPartCommissionDistributionAPI.js';
import { JobPartContentFileAPI } from '../api/JobPartContentFileAPI.js';
import { JobPartFinishingOpAPI } from '../api/JobPartFinishingOpAPI.js';
import { JobPartImpositionAllowanceAPI } from '../api/JobPartImpositionAllowanceAPI.js';
import { JobPartItemAPI } from '../api/JobPartItemAPI.js';
import { JobPartMailAPI } from '../api/JobPartMailAPI.js';
import { JobPartOptionAPI } from '../api/JobPartOptionAPI.js';
import { JobPartOutsidePurchAPI } from '../api/JobPartOutsidePurchAPI.js';
import { JobPartPrePressOpAPI } from '../api/JobPartPrePressOpAPI.js';
import { JobPartPressFormAPI } from '../api/JobPartPressFormAPI.js';
import { JobPartPressFormContentAPI } from '../api/JobPartPressFormContentAPI.js';
import { JobPartPressFormEventAPI } from '../api/JobPartPressFormEventAPI.js';
import { JobPartPressFormInkAPI } from '../api/JobPartPressFormInkAPI.js';
import { JobPartPressFormMixedMediaAPI } from '../api/JobPartPressFormMixedMediaAPI.js';
import { JobPartSalesDistAPI } from '../api/JobPartSalesDistAPI.js';
import { JobPartSalesDistLineAPI } from '../api/JobPartSalesDistLineAPI.js';
import { JobPartSizeAllowanceAPI } from '../api/JobPartSizeAllowanceAPI.js';
import { JobPlanAPI } from '../api/JobPlanAPI.js';
import { JobPlanDependanciesAPI } from '../api/JobPlanDependanciesAPI.js';
import { JobPlanLinkAPI } from '../api/JobPlanLinkAPI.js';
import { JobPlanSetupAPI } from '../api/JobPlanSetupAPI.js';
import { JobProductAPI } from '../api/JobProductAPI.js';
import { JobProductTypeAPI } from '../api/JobProductTypeAPI.js';
import { JobProjectAPI } from '../api/JobProjectAPI.js';
import { JobReorderAPI } from '../api/JobReorderAPI.js';
import { JobShipmentAPI } from '../api/JobShipmentAPI.js';
import { JobStatusAPI } from '../api/JobStatusAPI.js';
import { JobStatusReasonAPI } from '../api/JobStatusReasonAPI.js';
import { JobTrackingAPI } from '../api/JobTrackingAPI.js';
import { JobTypeAPI } from '../api/JobTypeAPI.js';
import { JobTypePlanAPI } from '../api/JobTypePlanAPI.js';
import { JoinedGroupAPI } from '../api/JoinedGroupAPI.js';
import { KeypadAPI } from '../api/KeypadAPI.js';
import { LanguageAPI } from '../api/LanguageAPI.js';
import { LanguageRegionAPI } from '../api/LanguageRegionAPI.js';
import { LegalEntityAPI } from '../api/LegalEntityAPI.js';
import { LinkAPI } from '../api/LinkAPI.js';
import { ListSourceAPI } from '../api/ListSourceAPI.js';
import { LocalFileAttachmentAPI } from '../api/LocalFileAttachmentAPI.js';
import { LookAndFeelAPI } from '../api/LookAndFeelAPI.js';
import { LotAPI } from '../api/LotAPI.js';
import { LotCycleCountAPI } from '../api/LotCycleCountAPI.js';
import { MailingClassAPI } from '../api/MailingClassAPI.js';
import { MailingSetupAPI } from '../api/MailingSetupAPI.js';
import { MailingSizeAPI } from '../api/MailingSizeAPI.js';
import { MailingTabsAPI } from '../api/MailingTabsAPI.js';
import { MailingTypeAPI } from '../api/MailingTypeAPI.js';
import { ManufacturingLocationAPI } from '../api/ManufacturingLocationAPI.js';
import { ManufacturingLocationShipDateTimeAPI } from '../api/ManufacturingLocationShipDateTimeAPI.js';
import { MasterBillOfLadingAPI } from '../api/MasterBillOfLadingAPI.js';
import { MaterialProvidedAPI } from '../api/MaterialProvidedAPI.js';
import { MerchantAccountAPI } from '../api/MerchantAccountAPI.js';
import { MetrixCutterOperationAPI } from '../api/MetrixCutterOperationAPI.js';
import { MetrixExportProfileAPI } from '../api/MetrixExportProfileAPI.js';
import { MetrixFinishingGroupAPI } from '../api/MetrixFinishingGroupAPI.js';
import { MetrixFoldPatternAPI } from '../api/MetrixFoldPatternAPI.js';
import { MetroAreaRelayAPI } from '../api/MetroAreaRelayAPI.js';
import { MetropolitanAreaAPI } from '../api/MetropolitanAreaAPI.js';
import { NetworkLocationAPI } from '../api/NetworkLocationAPI.js';
import { NonChargeableTimeAPI } from '../api/NonChargeableTimeAPI.js';
import { NonChargeableTypeAPI } from '../api/NonChargeableTypeAPI.js';
import { NonPlannedReasonAPI } from '../api/NonPlannedReasonAPI.js';
import { NoteCategoryAPI } from '../api/NoteCategoryAPI.js';
import { NotificationAPI } from '../api/NotificationAPI.js';
import { NotificationReadAPI } from '../api/NotificationReadAPI.js';
import { NotificationRecipientAPI } from '../api/NotificationRecipientAPI.js';
import { NotificationSetupAPI } from '../api/NotificationSetupAPI.js';
import { ObjectContextFilterRelationTypeAPI } from '../api/ObjectContextFilterRelationTypeAPI.js';
import { ObjectContextFilterTypeAPI } from '../api/ObjectContextFilterTypeAPI.js';
import { ObjectContextSecurityFilterAPI } from '../api/ObjectContextSecurityFilterAPI.js';
import { OpportunityAPI } from '../api/OpportunityAPI.js';
import { OpportunityTypeAPI } from '../api/OpportunityTypeAPI.js';
import { OptionAPI } from '../api/OptionAPI.js';
import { OptionListAPI } from '../api/OptionListAPI.js';
import { OrganizationAPI } from '../api/OrganizationAPI.js';
import { OrganizationCompanyAPI } from '../api/OrganizationCompanyAPI.js';
import { OrganizationSystemUserAPI } from '../api/OrganizationSystemUserAPI.js';
import { OrganizationSystemUserCompanyAPI } from '../api/OrganizationSystemUserCompanyAPI.js';
import { OutsidePurchaseDescriptionTemplateAPI } from '../api/OutsidePurchaseDescriptionTemplateAPI.js';
import { OutsidePurchaseTemplateAPI } from '../api/OutsidePurchaseTemplateAPI.js';
import { OutsidePurchaseVendorPriceAPI } from '../api/OutsidePurchaseVendorPriceAPI.js';
import { OutsidePurchaseWorkflowAPI } from '../api/OutsidePurchaseWorkflowAPI.js';
import { OutsidePurchaseWorkflowItemAPI } from '../api/OutsidePurchaseWorkflowItemAPI.js';
import { POSetupAPI } from '../api/POSetupAPI.js';
import { POStatusAPI } from '../api/POStatusAPI.js';
import { PaceConnectAPI } from '../api/PaceConnectAPI.js';
import { PaceConnectCommentAPI } from '../api/PaceConnectCommentAPI.js';
import { PaceConnectDatabaseConnectionAPI } from '../api/PaceConnectDatabaseConnectionAPI.js';
import { PaceConnectEventAPI } from '../api/PaceConnectEventAPI.js';
import { PaceConnectExpressionAPI } from '../api/PaceConnectExpressionAPI.js';
import { PaceConnectExpressionMapAPI } from '../api/PaceConnectExpressionMapAPI.js';
import { PaceConnectExternalExpressionAPI } from '../api/PaceConnectExternalExpressionAPI.js';
import { PaceConnectFailedOutputAPI } from '../api/PaceConnectFailedOutputAPI.js';
import { PaceConnectFieldMigrationAPI } from '../api/PaceConnectFieldMigrationAPI.js';
import { PaceConnectFileAPI } from '../api/PaceConnectFileAPI.js';
import { PaceConnectHeaderAPI } from '../api/PaceConnectHeaderAPI.js';
import { PaceConnectJMFMessageTypeAPI } from '../api/PaceConnectJMFMessageTypeAPI.js';
import { PaceConnectJMFQueueEntryAPI } from '../api/PaceConnectJMFQueueEntryAPI.js';
import { PaceConnectLocationAPI } from '../api/PaceConnectLocationAPI.js';
import { PaceConnectMapAPI } from '../api/PaceConnectMapAPI.js';
import { PaceConnectMapConfigAPI } from '../api/PaceConnectMapConfigAPI.js';
import { PaceConnectMapConfigEntryAPI } from '../api/PaceConnectMapConfigEntryAPI.js';
import { PaceConnectObjectMigrationAPI } from '../api/PaceConnectObjectMigrationAPI.js';
import { PaceConnectPendingFileAPI } from '../api/PaceConnectPendingFileAPI.js';
import { PaceConnectPendingFileParameterAPI } from '../api/PaceConnectPendingFileParameterAPI.js';
import { PaceConnectResultAPI } from '../api/PaceConnectResultAPI.js';
import { PaceConnectSizeMapAPI } from '../api/PaceConnectSizeMapAPI.js';
import { PaceConnectSyncAPI } from '../api/PaceConnectSyncAPI.js';
import { PaceQuoteSetupAPI } from '../api/PaceQuoteSetupAPI.js';
import { PaddingAPI } from '../api/PaddingAPI.js';
import { PaperCostAPI } from '../api/PaperCostAPI.js';
import { PaperSizeAPI } from '../api/PaperSizeAPI.js';
import { PaperSizeInventoryAPI } from '../api/PaperSizeInventoryAPI.js';
import { PaperTypeAPI } from '../api/PaperTypeAPI.js';
import { PaperTypeActivityAPI } from '../api/PaperTypeActivityAPI.js';
import { PaperWeightAPI } from '../api/PaperWeightAPI.js';
import { PatternCategoryAPI } from '../api/PatternCategoryAPI.js';
import { PatternSizeAllowanceAPI } from '../api/PatternSizeAllowanceAPI.js';
import { PaymentAPI } from '../api/PaymentAPI.js';
import { PaymentBatchAPI } from '../api/PaymentBatchAPI.js';
import { PaymentLineAPI } from '../api/PaymentLineAPI.js';
import { PaymentMethodAPI } from '../api/PaymentMethodAPI.js';
import { PayrollBatchAPI } from '../api/PayrollBatchAPI.js';
import { PayrollCheckAPI } from '../api/PayrollCheckAPI.js';
import { PayrollCheckLineAPI } from '../api/PayrollCheckLineAPI.js';
import { PayrollCheckTypeAPI } from '../api/PayrollCheckTypeAPI.js';
import { PayrollDeductionTypeAPI } from '../api/PayrollDeductionTypeAPI.js';
import { PayrollPayTypeAPI } from '../api/PayrollPayTypeAPI.js';
import { PayrollPayTypeExcludeDeductionAPI } from '../api/PayrollPayTypeExcludeDeductionAPI.js';
import { PayrollSetupAPI } from '../api/PayrollSetupAPI.js';
import { PayrollTaxTableAPI } from '../api/PayrollTaxTableAPI.js';
import { PayrollTaxTableLineAPI } from '../api/PayrollTaxTableLineAPI.js';
import { PermissionAPI } from '../api/PermissionAPI.js';
import { PermitBillingAPI } from '../api/PermitBillingAPI.js';
import { PermitPrintAPI } from '../api/PermitPrintAPI.js';
import { PermitUsedAPI } from '../api/PermitUsedAPI.js';
import { PersistentQueueAPI } from '../api/PersistentQueueAPI.js';
import { PlateAPI } from '../api/PlateAPI.js';
import { PostageTypeAPI } from '../api/PostageTypeAPI.js';
import { PrepActivityAPI } from '../api/PrepActivityAPI.js';
import { PrepMethodAPI } from '../api/PrepMethodAPI.js';
import { PrepressCostAPI } from '../api/PrepressCostAPI.js';
import { PrepressItemAPI } from '../api/PrepressItemAPI.js';
import { PrepressItemGroupAPI } from '../api/PrepressItemGroupAPI.js';
import { PrepressSizeAPI } from '../api/PrepressSizeAPI.js';
import { PrepressWorkflowAPI } from '../api/PrepressWorkflowAPI.js';
import { PressAPI } from '../api/PressAPI.js';
import { PressConsoleButtonAPI } from '../api/PressConsoleButtonAPI.js';
import { PressCutoffAPI } from '../api/PressCutoffAPI.js';
import { PressEventAPI } from '../api/PressEventAPI.js';
import { PressEventRunCostBasisAPI } from '../api/PressEventRunCostBasisAPI.js';
import { PressEventWorkflowAPI } from '../api/PressEventWorkflowAPI.js';
import { PressEventWorkflowItemAPI } from '../api/PressEventWorkflowItemAPI.js';
import { PressFeedDirectionAPI } from '../api/PressFeedDirectionAPI.js';
import { PressInkTypeAPI } from '../api/PressInkTypeAPI.js';
import { PressSpeedAPI } from '../api/PressSpeedAPI.js';
import { PressTypeAPI } from '../api/PressTypeAPI.js';
import { PressTypeInkTypeAPI } from '../api/PressTypeInkTypeAPI.js';
import { PressTypeSpeedMethodAPI } from '../api/PressTypeSpeedMethodAPI.js';
import { PreviousPasswordAPI } from '../api/PreviousPasswordAPI.js';
import { PriceAPI } from '../api/PriceAPI.js';
import { PriceDetailAPI } from '../api/PriceDetailAPI.js';
import { PriceListAPI } from '../api/PriceListAPI.js';
import { PriceListLineAPI } from '../api/PriceListLineAPI.js';
import { PrintCaseAPI } from '../api/PrintCaseAPI.js';
import { PrintRunMethodAPI } from '../api/PrintRunMethodAPI.js';
import { PrintServiceAPI } from '../api/PrintServiceAPI.js';
import { PrintTypeAPI } from '../api/PrintTypeAPI.js';
import { PrinterAPI } from '../api/PrinterAPI.js';
import { PrinterPaperMappingAPI } from '../api/PrinterPaperMappingAPI.js';
import { PrinterSettingsAPI } from '../api/PrinterSettingsAPI.js';
import { PrintstreamBatchAPI } from '../api/PrintstreamBatchAPI.js';
import { PrintstreamLotAPI } from '../api/PrintstreamLotAPI.js';
import { PriorityAPI } from '../api/PriorityAPI.js';
import { ProductAPI } from '../api/ProductAPI.js';
import { ProductExpressionAPI } from '../api/ProductExpressionAPI.js';
import { ProductGroupAPI } from '../api/ProductGroupAPI.js';
import { ProductItemAPI } from '../api/ProductItemAPI.js';
import { ProductOrderAPI } from '../api/ProductOrderAPI.js';
import { ProductPriceAPI } from '../api/ProductPriceAPI.js';
import { ProductQuantityAPI } from '../api/ProductQuantityAPI.js';
import { ProductTemplateAPI } from '../api/ProductTemplateAPI.js';
import { ProductTypeAPI } from '../api/ProductTypeAPI.js';
import { ProductionTypeAPI } from '../api/ProductionTypeAPI.js';
import { ProofAPI } from '../api/ProofAPI.js';
import { PurchaseOrderAPI } from '../api/PurchaseOrderAPI.js';
import { PurchaseOrderLineAPI } from '../api/PurchaseOrderLineAPI.js';
import { PurchaseOrderLineShipToAPI } from '../api/PurchaseOrderLineShipToAPI.js';
import { PurchaseOrderReceiptAPI } from '../api/PurchaseOrderReceiptAPI.js';
import { PurchaseOrderTypeAPI } from '../api/PurchaseOrderTypeAPI.js';
import { PurchasingAuthorizationAPI } from '../api/PurchasingAuthorizationAPI.js';
import { QuantityAPI } from '../api/QuantityAPI.js';
import { QuantityLabelAPI } from '../api/QuantityLabelAPI.js';
import { QuantityPriceDiscountAPI } from '../api/QuantityPriceDiscountAPI.js';
import { QuestionAPI } from '../api/QuestionAPI.js';
import { QuestionnairePartAPI } from '../api/QuestionnairePartAPI.js';
import { QuestionnaireProductAPI } from '../api/QuestionnaireProductAPI.js';
import { QuestionnaireResponseAPI } from '../api/QuestionnaireResponseAPI.js';
import { QuestionnaireStatusAPI } from '../api/QuestionnaireStatusAPI.js';
import { QuestionnaireTopicAPI } from '../api/QuestionnaireTopicAPI.js';
import { QuestionnaireTypeAPI } from '../api/QuestionnaireTypeAPI.js';
import { QueuedNotificationAPI } from '../api/QueuedNotificationAPI.js';
import { QuoteAPI } from '../api/QuoteAPI.js';
import { QuoteCalcMessageAPI } from '../api/QuoteCalcMessageAPI.js';
import { QuoteCategoryAPI } from '../api/QuoteCategoryAPI.js';
import { QuoteCategoryGroupAPI } from '../api/QuoteCategoryGroupAPI.js';
import { QuoteComponentAPI } from '../api/QuoteComponentAPI.js';
import { QuoteDepartmentAPI } from '../api/QuoteDepartmentAPI.js';
import { QuoteExpressionAPI } from '../api/QuoteExpressionAPI.js';
import { QuoteItemAPI } from '../api/QuoteItemAPI.js';
import { QuoteItemPriceAPI } from '../api/QuoteItemPriceAPI.js';
import { QuoteItemTypeAPI } from '../api/QuoteItemTypeAPI.js';
import { QuoteItemTypeActivityCodeAPI } from '../api/QuoteItemTypeActivityCodeAPI.js';
import { QuoteItemTypeInventoryItemAPI } from '../api/QuoteItemTypeInventoryItemAPI.js';
import { QuoteItemTypePrintServiceAPI } from '../api/QuoteItemTypePrintServiceAPI.js';
import { QuoteItemTypeUdfAPI } from '../api/QuoteItemTypeUdfAPI.js';
import { QuoteLetterAPI } from '../api/QuoteLetterAPI.js';
import { QuoteLetterNoteAPI } from '../api/QuoteLetterNoteAPI.js';
import { QuoteLetterTextAPI } from '../api/QuoteLetterTextAPI.js';
import { QuoteLetterTypeAPI } from '../api/QuoteLetterTypeAPI.js';
import { QuoteLetterTypeTextAPI } from '../api/QuoteLetterTypeTextAPI.js';
import { QuoteNoteAPI } from '../api/QuoteNoteAPI.js';
import { QuotePriceAPI } from '../api/QuotePriceAPI.js';
import { QuoteProductAPI } from '../api/QuoteProductAPI.js';
import { QuoteProductContentFileAPI } from '../api/QuoteProductContentFileAPI.js';
import { QuoteQuantityAPI } from '../api/QuoteQuantityAPI.js';
import { QuoteShipmentAPI } from '../api/QuoteShipmentAPI.js';
import { RSSChannelAPI } from '../api/RSSChannelAPI.js';
import { RateLevelAPI } from '../api/RateLevelAPI.js';
import { ReceivableAPI } from '../api/ReceivableAPI.js';
import { ReceivableLineAPI } from '../api/ReceivableLineAPI.js';
import { ReceivablePaymentGroupAPI } from '../api/ReceivablePaymentGroupAPI.js';
import { ReceivablePaymentGroupLineAPI } from '../api/ReceivablePaymentGroupLineAPI.js';
import { RecentItemAPI } from '../api/RecentItemAPI.js';
import { RecurrenceAPI } from '../api/RecurrenceAPI.js';
import { RelatedInventoryItemsAPI } from '../api/RelatedInventoryItemsAPI.js';
import { RelayDateTimeAPI } from '../api/RelayDateTimeAPI.js';
import { ReportAPI } from '../api/ReportAPI.js';
import { ReportCategoryAPI } from '../api/ReportCategoryAPI.js';
import { ReportConditionAPI } from '../api/ReportConditionAPI.js';
import { ReportEmailRecipientAPI } from '../api/ReportEmailRecipientAPI.js';
import { ReportFileAPI } from '../api/ReportFileAPI.js';
import { ReportPackageAPI } from '../api/ReportPackageAPI.js';
import { ReportPackageEntryAPI } from '../api/ReportPackageEntryAPI.js';
import { ReportPackageEntryParameterAPI } from '../api/ReportPackageEntryParameterAPI.js';
import { ReportPaperAPI } from '../api/ReportPaperAPI.js';
import { ReportParameterAPI } from '../api/ReportParameterAPI.js';
import { ReportPrinterAPI } from '../api/ReportPrinterAPI.js';
import { ReportSettingsAPI } from '../api/ReportSettingsAPI.js';
import { ReportVersionCategoryAPI } from '../api/ReportVersionCategoryAPI.js';
import { ReturnPrintAPI } from '../api/ReturnPrintAPI.js';
import { RevenueTypeAPI } from '../api/RevenueTypeAPI.js';
import { RevisionAPI } from '../api/RevisionAPI.js';
import { RouterAPI } from '../api/RouterAPI.js';
import { RoutingTemplateAPI } from '../api/RoutingTemplateAPI.js';
import { RoutingTemplateOrderAPI } from '../api/RoutingTemplateOrderAPI.js';
import { RoutingTemplateOrderActivityCodeAPI } from '../api/RoutingTemplateOrderActivityCodeAPI.js';
import { RushChargeAPI } from '../api/RushChargeAPI.js';
import { SalesCategoryAPI } from '../api/SalesCategoryAPI.js';
import { SalesCategoryTaxRateAPI } from '../api/SalesCategoryTaxRateAPI.js';
import { SalesPersonAPI } from '../api/SalesPersonAPI.js';
import { SalesStageAPI } from '../api/SalesStageAPI.js';
import { SalesTaxAPI } from '../api/SalesTaxAPI.js';
import { SalutationAPI } from '../api/SalutationAPI.js';
import { SamplesAPI } from '../api/SamplesAPI.js';
import { ScheduleStatusAPI } from '../api/ScheduleStatusAPI.js';
import { ScheduledTaskAPI } from '../api/ScheduledTaskAPI.js';
import { ScheduledTaskEmailRecipientAPI } from '../api/ScheduledTaskEmailRecipientAPI.js';
import { ScheduledTaskNotificationRecipientAPI } from '../api/ScheduledTaskNotificationRecipientAPI.js';
import { ScheduledTaskOutputLocationAPI } from '../api/ScheduledTaskOutputLocationAPI.js';
import { ScheduledTaskParameterAPI } from '../api/ScheduledTaskParameterAPI.js';
import { ScheduledTaskResultAPI } from '../api/ScheduledTaskResultAPI.js';
import { SchedulingFlagAPI } from '../api/SchedulingFlagAPI.js';
import { SecurityFilterAPI } from '../api/SecurityFilterAPI.js';
import { SecurityFilterItemAPI } from '../api/SecurityFilterItemAPI.js';
import { SecurityFilterRelationTypeAPI } from '../api/SecurityFilterRelationTypeAPI.js';
import { SecurityFilterTypeAPI } from '../api/SecurityFilterTypeAPI.js';
import { ShipProviderAPI } from '../api/ShipProviderAPI.js';
import { ShipRateSheetEntryAPI } from '../api/ShipRateSheetEntryAPI.js';
import { ShipViaAPI } from '../api/ShipViaAPI.js';
import { ShipZoneAPI } from '../api/ShipZoneAPI.js';
import { ShipZonePostalCodeAPI } from '../api/ShipZonePostalCodeAPI.js';
import { ShipmentDistributionAPI } from '../api/ShipmentDistributionAPI.js';
import { ShipmentTypeAPI } from '../api/ShipmentTypeAPI.js';
import { ShippingAppSettingsAPI } from '../api/ShippingAppSettingsAPI.js';
import { ShippingWorkflowAPI } from '../api/ShippingWorkflowAPI.js';
import { ShippingWorkflowFinishingOpAPI } from '../api/ShippingWorkflowFinishingOpAPI.js';
import { ShoppingCartAPI } from '../api/ShoppingCartAPI.js';
import { ShoppingCartExtraAPI } from '../api/ShoppingCartExtraAPI.js';
import { ShoppingCartExtraTemplateAPI } from '../api/ShoppingCartExtraTemplateAPI.js';
import { SizeAPI } from '../api/SizeAPI.js';
import { SizeAllowanceTypeAPI } from '../api/SizeAllowanceTypeAPI.js';
import { SkidAPI } from '../api/SkidAPI.js';
import { SourceTypeAPI } from '../api/SourceTypeAPI.js';
import { SpeedFactorAPI } from '../api/SpeedFactorAPI.js';
import { StandardPaperTypeAPI } from '../api/StandardPaperTypeAPI.js';
import { StateAPI } from '../api/StateAPI.js';
import { StatusTypeAPI } from '../api/StatusTypeAPI.js';
import { SubJobTypeAPI } from '../api/SubJobTypeAPI.js';
import { SubNoteCategoryAPI } from '../api/SubNoteCategoryAPI.js';
import { SubProductGroupAPI } from '../api/SubProductGroupAPI.js';
import { SuggestedRollAPI } from '../api/SuggestedRollAPI.js';
import { SystemGroupAPI } from '../api/SystemGroupAPI.js';
import { SystemUserAPI } from '../api/SystemUserAPI.js';
import { TagAPI } from '../api/TagAPI.js';
import { TagCategoryAPI } from '../api/TagCategoryAPI.js';
import { TaxCategoryAPI } from '../api/TaxCategoryAPI.js';
import { TaxReportAPI } from '../api/TaxReportAPI.js';
import { TaxReportCategoryAPI } from '../api/TaxReportCategoryAPI.js';
import { TaxReportMonthAPI } from '../api/TaxReportMonthAPI.js';
import { TaxReportPeriodAPI } from '../api/TaxReportPeriodAPI.js';
import { TaxReportPeriodCategoryAPI } from '../api/TaxReportPeriodCategoryAPI.js';
import { TaxReportPeriodCategorySalesTaxAPI } from '../api/TaxReportPeriodCategorySalesTaxAPI.js';
import { TaxReportPeriodMonthMappingAPI } from '../api/TaxReportPeriodMonthMappingAPI.js';
import { TaxableCodeAPI } from '../api/TaxableCodeAPI.js';
import { TermsAPI } from '../api/TermsAPI.js';
import { TermsDiscountAPI } from '../api/TermsDiscountAPI.js';
import { ThreeKnifeAPI } from '../api/ThreeKnifeAPI.js';
import { TopicAPI } from '../api/TopicAPI.js';
import { TopicQuestionAPI } from '../api/TopicQuestionAPI.js';
import { TopicQuestionResponseHandlerAPI } from '../api/TopicQuestionResponseHandlerAPI.js';
import { TwitterAccountAPI } from '../api/TwitterAccountAPI.js';
import { UOMAPI } from '../api/UOMAPI.js';
import { UOMDimensionAPI } from '../api/UOMDimensionAPI.js';
import { UOMRangeAPI } from '../api/UOMRangeAPI.js';
import { UOMSetupAPI } from '../api/UOMSetupAPI.js';
import { UOMTypeAPI } from '../api/UOMTypeAPI.js';
import { UserDefinedContextAPI } from '../api/UserDefinedContextAPI.js';
import { UserDefinedFormAPI } from '../api/UserDefinedFormAPI.js';
import { UserDefinedFormExtractedObjectAPI } from '../api/UserDefinedFormExtractedObjectAPI.js';
import { UserDefinedFormRequiredObjectAPI } from '../api/UserDefinedFormRequiredObjectAPI.js';
import { UserDefinedIncludableFormAPI } from '../api/UserDefinedIncludableFormAPI.js';
import { UserDefinedInquiryAPI } from '../api/UserDefinedInquiryAPI.js';
import { UserDefinedInquiryCategoryAPI } from '../api/UserDefinedInquiryCategoryAPI.js';
import { UserDefinedInquiryContextMenuObjectAPI } from '../api/UserDefinedInquiryContextMenuObjectAPI.js';
import { UserDefinedInquiryRecipientAPI } from '../api/UserDefinedInquiryRecipientAPI.js';
import { UserDefinedMenuAPI } from '../api/UserDefinedMenuAPI.js';
import { UserDefinedMenuItemAPI } from '../api/UserDefinedMenuItemAPI.js';
import { UserDefinedViewAPI } from '../api/UserDefinedViewAPI.js';
import { UserFormAPI } from '../api/UserFormAPI.js';
import { UserInterfaceSetAPI } from '../api/UserInterfaceSetAPI.js';
import { VelocityTemplateAPI } from '../api/VelocityTemplateAPI.js';
import { VendorAPI } from '../api/VendorAPI.js';
import { VendorCertificationAPI } from '../api/VendorCertificationAPI.js';
import { VendorNoteAPI } from '../api/VendorNoteAPI.js';
import { VendorPaperAPI } from '../api/VendorPaperAPI.js';
import { VendorPaperPriceAPI } from '../api/VendorPaperPriceAPI.js';
import { VendorTypeAPI } from '../api/VendorTypeAPI.js';
import { VirtualPrinterAPI } from '../api/VirtualPrinterAPI.js';
import { WIPCategoryAPI } from '../api/WIPCategoryAPI.js';
import { WorkstationAPI } from '../api/WorkstationAPI.js';
import { WorkstationActivityCodeAPI } from '../api/WorkstationActivityCodeAPI.js';
import { WorkstationEmployeeAPI } from '../api/WorkstationEmployeeAPI.js';
import { WorkstationInventoryItemAPI } from '../api/WorkstationInventoryItemAPI.js';
import { WorkstationNonChargeableTypeAPI } from '../api/WorkstationNonChargeableTypeAPI.js';
import { WorkstationNonPlannedReasonAPI } from '../api/WorkstationNonPlannedReasonAPI.js';
import { WrapStyleAPI } from '../api/WrapStyleAPI.js';

export class PaceClient {
    constructor({ username, password, baseUrl }) {
        const client = new HttpClient({ baseUrl, username, password });
        this.apsetup = new APSetupAPI(client);
        this.arsetup = new ARSetupAPI(client);
        this.activity = new ActivityAPI(client);
        this.activitycode = new ActivityCodeAPI(client);
        this.activitycodehotkey = new ActivityCodeHotkeyAPI(client);
        this.activitycodeinventoryitemtype = new ActivityCodeInventoryItemTypeAPI(client);
        this.activitycodeplqmapping = new ActivityCodePLQMappingAPI(client);
        this.activitycodeupstreamdependencies = new ActivityCodeUpstreamDependenciesAPI(client);
        this.activityrate = new ActivityRateAPI(client);
        this.activityratemarkup = new ActivityRateMarkupAPI(client);
        this.activitytype = new ActivityTypeAPI(client);
        this.addressformat = new AddressFormatAPI(client);
        this.allowanceexpression = new AllowanceExpressionAPI(client);
        this.alternateprintmethod = new AlternatePrintMethodAPI(client);
        this.alternateprintmethodcontent = new AlternatePrintMethodContentAPI(client);
        this.approvalgroup = new ApprovalGroupAPI(client);
        this.assetclass = new AssetClassAPI(client);
        this.assetdepbatch = new AssetDepBatchAPI(client);
        this.assetdepline = new AssetDepLineAPI(client);
        this.assetpostinggroup = new AssetPostingGroupAPI(client);
        this.assettransaction = new AssetTransactionAPI(client);
        this.assettransactionbatch = new AssetTransactionBatchAPI(client);
        this.attachmentcategory = new AttachmentCategoryAPI(client);
        this.attachmentrule = new AttachmentRuleAPI(client);
        this.attachmentsetup = new AttachmentSetupAPI(client);
        this.autobill = new AutoBillAPI(client);
        this.autobillline = new AutoBillLineAPI(client);
        this.autoinvoice = new AutoInvoiceAPI(client);
        this.autoinvoiceline = new AutoInvoiceLineAPI(client);
        this.bankaccount = new BankAccountAPI(client);
        this.bankaccountline = new BankAccountLineAPI(client);
        this.bankstatement = new BankStatementAPI(client);
        this.bill = new BillAPI(client);
        this.billbatch = new BillBatchAPI(client);
        this.billcheck = new BillCheckAPI(client);
        this.billline = new BillLineAPI(client);
        this.billoflading = new BillOfLadingAPI(client);
        this.billpayment = new BillPaymentAPI(client);
        this.billpaymentbatch = new BillPaymentBatchAPI(client);
        this.billstatus = new BillStatusAPI(client);
        this.binder = new BinderAPI(client);
        this.binderspeed = new BinderSpeedAPI(client);
        this.bindingmethod = new BindingMethodAPI(client);
        this.bindingmethodfinishingop = new BindingMethodFinishingOpAPI(client);
        this.crmsetup = new CRMSetupAPI(client);
        this.crmstatus = new CRMStatusAPI(client);
        this.crmuser = new CRMUserAPI(client);
        this.csr = new CSRAPI(client);
        this.campaign = new CampaignAPI(client);
        this.campaignnote = new CampaignNoteAPI(client);
        this.campaigntype = new CampaignTypeAPI(client);
        this.carton = new CartonAPI(client);
        this.cartoncontent = new CartonContentAPI(client);
        this.certificationauthority = new CertificationAuthorityAPI(client);
        this.certificationlevel = new CertificationLevelAPI(client);
        this.certificationproductclassification = new CertificationProductClassificationAPI(client);
        this.certificationtraining = new CertificationTrainingAPI(client);
        this.changeorder = new ChangeOrderAPI(client);
        this.changeorderline = new ChangeOrderLineAPI(client);
        this.changeordertype = new ChangeOrderTypeAPI(client);
        this.chargebackaccount = new ChargeBackAccountAPI(client);
        this.combojob = new ComboJobAPI(client);
        this.company = new CompanyAPI(client);
        this.componenttype = new ComponentTypeAPI(client);
        this.contact = new ContactAPI(client);
        this.contactnote = new ContactNoteAPI(client);
        this.contentfile = new ContentFileAPI(client);
        this.contentfilecategory = new ContentFileCategoryAPI(client);
        this.contentfilecontour = new ContentFileContourAPI(client);
        this.costcategory = new CostCategoryAPI(client);
        this.costcenter = new CostCenterAPI(client);
        this.costcentertype = new CostCenterTypeAPI(client);
        this.country = new CountryAPI(client);
        this.countrygroup = new CountryGroupAPI(client);
        this.countrygroupmember = new CountryGroupMemberAPI(client);
        this.currency = new CurrencyAPI(client);
        this.currencyexchangerate = new CurrencyExchangeRateAPI(client);
        this.customer = new CustomerAPI(client);
        this.customercalculate = new CustomerCalculateAPI(client);
        this.customercommissiondistribution = new CustomerCommissionDistributionAPI(client);
        this.customergroup = new CustomerGroupAPI(client);
        this.customergroupdiscount = new CustomerGroupDiscountAPI(client);
        this.customernote = new CustomerNoteAPI(client);
        this.customerpaymentmethod = new CustomerPaymentMethodAPI(client);
        this.customershoppingcartextra = new CustomerShoppingCartExtraAPI(client);
        this.customerstatus = new CustomerStatusAPI(client);
        this.customertype = new CustomerTypeAPI(client);
        this.cutter = new CutterAPI(client);
        this.cutteralignmentmarkgroup = new CutterAlignmentMarkGroupAPI(client);
        this.cyclecount = new CycleCountAPI(client);
        this.dsfentity = new DSFEntityAPI(client);
        this.dsfmediasize = new DSFMediaSizeAPI(client);
        this.dsforderstatus = new DSFOrderStatusAPI(client);
        this.datacollectionsetup = new DataCollectionSetupAPI(client);
        this.defaultestimatefinishingop = new DefaultEstimateFinishingOpAPI(client);
        this.defaultestimateoption = new DefaultEstimateOptionAPI(client);
        this.department = new DepartmentAPI(client);
        this.depreciationmethod = new DepreciationMethodAPI(client);
        this.detailuom = new DetailUOMAPI(client);
        this.devicecapability = new DeviceCapabilityAPI(client);
        this.digitalworkflowsetup = new DigitalWorkflowSetupAPI(client);
        this.disallowedautochangeabletojobstatus = new DisAllowedAutoChangeableToJobStatusAPI(client);
        this.distribution = new DistributionAPI(client);
        this.dunningletter = new DunningLetterAPI(client);
        this.epacestationsetup = new EPaceStationSetupAPI(client);
        this.emailtemplate = new EmailTemplateAPI(client);
        this.emailtemplatecategory = new EmailTemplateCategoryAPI(client);
        this.employee = new EmployeeAPI(client);
        this.employeecounttype = new EmployeeCountTypeAPI(client);
        this.employeehotkey = new EmployeeHotkeyAPI(client);
        this.employeenote = new EmployeeNoteAPI(client);
        this.employeepayrolldeduction = new EmployeePayrollDeductionAPI(client);
        this.employeestatus = new EmployeeStatusAPI(client);
        this.employeetime = new EmployeeTimeAPI(client);
        this.employeetimesession = new EmployeeTimeSessionAPI(client);
        this.eservicesetup = new EserviceSetupAPI(client);
        this.estimate = new EstimateAPI(client);
        this.estimateactivity = new EstimateActivityAPI(client);
        this.estimatecalcmessage = new EstimateCalcMessageAPI(client);
        this.estimatecarton = new EstimateCartonAPI(client);
        this.estimatecartoncontent = new EstimateCartonContentAPI(client);
        this.estimatecomponent = new EstimateComponentAPI(client);
        this.estimatecompositeproduct = new EstimateCompositeProductAPI(client);
        this.estimatecompositeproductentry = new EstimateCompositeProductEntryAPI(client);
        this.estimateexpression = new EstimateExpressionAPI(client);
        this.estimatefinishingop = new EstimateFinishingOpAPI(client);
        this.estimateintentinfo = new EstimateIntentInfoAPI(client);
        this.estimateitem = new EstimateItemAPI(client);
        this.estimatelayout = new EstimateLayoutAPI(client);
        this.estimatelayoutcontent = new EstimateLayoutContentAPI(client);
        this.estimatemail = new EstimateMailAPI(client);
        this.estimatematerial = new EstimateMaterialAPI(client);
        this.estimatenote = new EstimateNoteAPI(client);
        this.estimateoption = new EstimateOptionAPI(client);
        this.estimateoutsidepurch = new EstimateOutsidePurchAPI(client);
        this.estimatepaper = new EstimatePaperAPI(client);
        this.estimatepart = new EstimatePartAPI(client);
        this.estimatepartcontentfile = new EstimatePartContentFileAPI(client);
        this.estimatepartimpositionallowance = new EstimatePartImpositionAllowanceAPI(client);
        this.estimatepartsizeallowance = new EstimatePartSizeAllowanceAPI(client);
        this.estimateprepressop = new EstimatePrepressOpAPI(client);
        this.estimatepress = new EstimatePressAPI(client);
        this.estimatepresscontent = new EstimatePressContentAPI(client);
        this.estimatepressevent = new EstimatePressEventAPI(client);
        this.estimatepressink = new EstimatePressInkAPI(client);
        this.estimatepressmixedmedia = new EstimatePressMixedMediaAPI(client);
        this.estimatepricesummary = new EstimatePriceSummaryAPI(client);
        this.estimateproduct = new EstimateProductAPI(client);
        this.estimateproductcategory = new EstimateProductCategoryAPI(client);
        this.estimateproductcategoryjobproducttype = new EstimateProductCategoryJobProductTypeAPI(client);
        this.estimateproductpricesummary = new EstimateProductPriceSummaryAPI(client);
        this.estimatequantity = new EstimateQuantityAPI(client);
        this.estimatequantitycommissiondistribution = new EstimateQuantityCommissionDistributionAPI(client);
        this.estimatequantitycontributionanalysis = new EstimateQuantityContributionAnalysisAPI(client);
        this.estimatequoteletter = new EstimateQuoteLetterAPI(client);
        this.estimatequoteletternote = new EstimateQuoteLetterNoteAPI(client);
        this.estimatequoteletternoteprice = new EstimateQuoteLetterNotePriceAPI(client);
        this.estimaterequest = new EstimateRequestAPI(client);
        this.estimaterequestcomponent = new EstimateRequestComponentAPI(client);
        this.estimaterequestfinishingop = new EstimateRequestFinishingOpAPI(client);
        this.estimaterequestitem = new EstimateRequestItemAPI(client);
        this.estimaterequestmaterial = new EstimateRequestMaterialAPI(client);
        this.estimaterequestnote = new EstimateRequestNoteAPI(client);
        this.estimaterequestoption = new EstimateRequestOptionAPI(client);
        this.estimaterequestpart = new EstimateRequestPartAPI(client);
        this.estimaterequestpartsizeallowance = new EstimateRequestPartSizeAllowanceAPI(client);
        this.estimaterequestprepressop = new EstimateRequestPrepressOpAPI(client);
        this.estimaterequestpressevent = new EstimateRequestPressEventAPI(client);
        this.estimaterequestproduct = new EstimateRequestProductAPI(client);
        this.estimaterequestsetup = new EstimateRequestSetupAPI(client);
        this.estimaterequeststatus = new EstimateRequestStatusAPI(client);
        this.estimatesetup = new EstimateSetupAPI(client);
        this.estimateshipment = new EstimateShipmentAPI(client);
        this.estimateskid = new EstimateSkidAPI(client);
        this.estimatestatus = new EstimateStatusAPI(client);
        this.estimatevariantset = new EstimateVariantSetAPI(client);
        this.estimatevariantsetentry = new EstimateVariantSetEntryAPI(client);
        this.estimatedpricingpolicy = new EstimatedPricingPolicyAPI(client);
        this.estimator = new EstimatorAPI(client);
        this.eventhandlerconditiondefinition = new EventHandlerConditionDefinitionAPI(client);
        this.eventhandlerdefinition = new EventHandlerDefinitionAPI(client);
        this.eventhandleremailconsequencedefinition = new EventHandlerEmailConsequenceDefinitionAPI(client);
        this.eventhandleremailrecipient = new EventHandlerEmailRecipientAPI(client);
        this.eventhandleremailreportattachment = new EventHandlerEmailReportAttachmentAPI(client);
        this.eventhandlereventdefinition = new EventHandlerEventDefinitionAPI(client);
        this.eventhandlerexecuteconnectdefinition = new EventHandlerExecuteConnectDefinitionAPI(client);
        this.eventhandlernotificationconsequencedefinition = new EventHandlerNotificationConsequenceDefinitionAPI(client);
        this.eventhandlernotificationrecipient = new EventHandlerNotificationRecipientAPI(client);
        this.eventhandlerprintreportdefinition = new EventHandlerPrintReportDefinitionAPI(client);
        this.expression = new ExpressionAPI(client);
        this.expressioncategory = new ExpressionCategoryAPI(client);
        this.externalbodprimarykeyreference = new ExternalBODPrimaryKeyReferenceAPI(client);
        this.extrastock = new ExtraStockAPI(client);
        this.fasetup = new FASetupAPI(client);
        this.facebookaccount = new FacebookAccountAPI(client);
        this.fileattachment = new FileAttachmentAPI(client);
        this.fileattachmentmeta = new FileAttachmentMetaAPI(client);
        this.filetype = new FileTypeAPI(client);
        this.fingoodsorder = new FinGoodsOrderAPI(client);
        this.finishingmachinetype = new FinishingMachineTypeAPI(client);
        this.finishingoperation = new FinishingOperationAPI(client);
        this.finishingoperationdisplayattribute = new FinishingOperationDisplayAttributeAPI(client);
        this.finishingoperationgroup = new FinishingOperationGroupAPI(client);
        this.finishingoperationmaterial = new FinishingOperationMaterialAPI(client);
        this.finishingoperationspeed = new FinishingOperationSpeedAPI(client);
        this.fixedasset = new FixedAssetAPI(client);
        this.fixedassetnote = new FixedAssetNoteAPI(client);
        this.foldpattern = new FoldPatternAPI(client);
        this.folder = new FolderAPI(client);
        this.folderspeed = new FolderSpeedAPI(client);
        this.font = new FontAPI(client);
        this.freightclassification = new FreightClassificationAPI(client);
        this.freightlinkupsentry = new FreightLinkUPSEntryAPI(client);
        this.fulfillmentsetup = new FulfillmentSetupAPI(client);
        this.glaccount = new GLAccountAPI(client);
        this.glaccountbalance = new GLAccountBalanceAPI(client);
        this.glaccountbalancesummary = new GLAccountBalanceSummaryAPI(client);
        this.glaccountbudget = new GLAccountBudgetAPI(client);
        this.glaccountingperiod = new GLAccountingPeriodAPI(client);
        this.glaccountingperiodsummaryname = new GLAccountingPeriodSummaryNameAPI(client);
        this.glbatch = new GLBatchAPI(client);
        this.gldepartment = new GLDepartmentAPI(client);
        this.gldepartmentlocation = new GLDepartmentLocationAPI(client);
        this.gljournalentry = new GLJournalEntryAPI(client);
        this.gljournalentryaudit = new GLJournalEntryAuditAPI(client);
        this.gllocation = new GLLocationAPI(client);
        this.glregisternumber = new GLRegisterNumberAPI(client);
        this.glschedule = new GLScheduleAPI(client);
        this.glscheduleline = new GLScheduleLineAPI(client);
        this.glsetup = new GLSetupAPI(client);
        this.glsplit = new GLSplitAPI(client);
        this.glsummaryname = new GLSummaryNameAPI(client);
        this.genericfinishingmachine = new GenericFinishingMachineAPI(client);
        this.genericfinishingspeed = new GenericFinishingSpeedAPI(client);
        this.howtodedupe = new HowToDeDupeAPI(client);
        this.i18nbundle = new I18nBundleAPI(client);
        this.importcontrol = new ImportControlAPI(client);
        this.importelement = new ImportElementAPI(client);
        this.importtemplate = new ImportTemplateAPI(client);
        this.importtemplatecategory = new ImportTemplateCategoryAPI(client);
        this.importtemplateobjectnode = new ImportTemplateObjectNodeAPI(client);
        this.importtemplateparameter = new ImportTemplateParameterAPI(client);
        this.importtemplatexpathvariable = new ImportTemplateXPathVariableAPI(client);
        this.indexmetadata = new IndexMetaDataAPI(client);
        this.industrytype = new IndustryTypeAPI(client);
        this.ink = new InkAPI(client);
        this.inkdefault = new InkDefaultAPI(client);
        this.inkdefaultink = new InkDefaultInkAPI(client);
        this.inquirydefinition = new InquiryDefinitionAPI(client);
        this.inserttype = new InsertTypeAPI(client);
        this.installationtool = new InstallationToolAPI(client);
        this.installationtoolcategory = new InstallationToolCategoryAPI(client);
        this.installationtoolchecklist = new InstallationToolChecklistAPI(client);
        this.inventorybatch = new InventoryBatchAPI(client);
        this.inventorybin = new InventoryBinAPI(client);
        this.inventorybinquantity = new InventoryBinQuantityAPI(client);
        this.inventoryconversion = new InventoryConversionAPI(client);
        this.inventoryconversiontarget = new InventoryConversionTargetAPI(client);
        this.inventoryitem = new InventoryItemAPI(client);
        this.inventoryitemcertification = new InventoryItemCertificationAPI(client);
        this.inventoryitemkit = new InventoryItemKitAPI(client);
        this.inventoryitemmanufacturinglocation = new InventoryItemManufacturingLocationAPI(client);
        this.inventoryitempurchaseuom = new InventoryItemPurchaseUomAPI(client);
        this.inventoryitemtype = new InventoryItemTypeAPI(client);
        this.inventoryitemvendor = new InventoryItemVendorAPI(client);
        this.inventoryitemvendorcost = new InventoryItemVendorCostAPI(client);
        this.inventoryline = new InventoryLineAPI(client);
        this.inventorylocation = new InventoryLocationAPI(client);
        this.inventorylocationquantity = new InventoryLocationQuantityAPI(client);
        this.inventorysetup = new InventorySetupAPI(client);
        this.inventorystatus = new InventoryStatusAPI(client);
        this.inventorytrntype = new InventoryTrnTypeAPI(client);
        this.invoice = new InvoiceAPI(client);
        this.invoicebatch = new InvoiceBatchAPI(client);
        this.invoicebodidlink = new InvoiceBodIDLinkAPI(client);
        this.invoicecommdist = new InvoiceCommDistAPI(client);
        this.invoiceextra = new InvoiceExtraAPI(client);
        this.invoiceextratype = new InvoiceExtraTypeAPI(client);
        this.invoiceline = new InvoiceLineAPI(client);
        this.invoicesalesdist = new InvoiceSalesDistAPI(client);
        this.invoicesource = new InvoiceSourceAPI(client);
        this.invoicetaxdist = new InvoiceTaxDistAPI(client);
        this.invoicetype = new InvoiceTypeAPI(client);
        this.issue = new IssueAPI(client);
        this.issuecomment = new IssueCommentAPI(client);
        this.issueresolution = new IssueResolutionAPI(client);
        this.issuestatus = new IssueStatusAPI(client);
        this.issuesubtype = new IssueSubTypeAPI(client);
        this.issuetype = new IssueTypeAPI(client);
        this.itemtemplate = new ItemTemplateAPI(client);
        this.itemtemplatecombolink = new ItemTemplateComboLinkAPI(client);
        this.itemtemplateline = new ItemTemplateLineAPI(client);
        this.itemtemplatelineattribute = new ItemTemplateLineAttributeAPI(client);
        this.itemtemplateproducttype = new ItemTemplateProductTypeAPI(client);
        this.itemtemplateproducttypeitem = new ItemTemplateProductTypeItemAPI(client);
        this.itemtemplateproducttypemapping = new ItemTemplateProductTypeMappingAPI(client);
        this.itemtemplatequantity = new ItemTemplateQuantityAPI(client);
        this.itemtemplatesetup = new ItemTemplateSetupAPI(client);
        this.itemtemplatetype = new ItemTemplateTypeAPI(client);
        this.jmfreceivedmessage = new JMFReceivedMessageAPI(client);
        this.jmfreceivedmessagepartition = new JMFReceivedMessagePartitionAPI(client);
        this.jmfreceivedmessagetransaction = new JMFReceivedMessageTransactionAPI(client);
        this.jmfreceivedmessagetransactionpartition = new JMFReceivedMessageTransactionPartitionAPI(client);
        this.job = new JobAPI(client);
        this.jobarchive = new JobArchiveAPI(client);
        this.jobbillingaccountingcode = new JobBillingAccountingCodeAPI(client);
        this.jobbillingsetup = new JobBillingSetupAPI(client);
        this.jobcomponent = new JobComponentAPI(client);
        this.jobcontact = new JobContactAPI(client);
        this.jobcontrolsetup = new JobControlSetupAPI(client);
        this.jobcost = new JobCostAPI(client);
        this.jobcostsetup = new JobCostSetupAPI(client);
        this.jobcosttype = new JobCostTypeAPI(client);
        this.jobdifficulty = new JobDifficultyAPI(client);
        this.jobdiscount = new JobDiscountAPI(client);
        this.jobmaterial = new JobMaterialAPI(client);
        this.jobnote = new JobNoteAPI(client);
        this.jobover = new JobOverAPI(client);
        this.jobpart = new JobPartAPI(client);
        this.jobpartcommissiondistribution = new JobPartCommissionDistributionAPI(client);
        this.jobpartcontentfile = new JobPartContentFileAPI(client);
        this.jobpartfinishingop = new JobPartFinishingOpAPI(client);
        this.jobpartimpositionallowance = new JobPartImpositionAllowanceAPI(client);
        this.jobpartitem = new JobPartItemAPI(client);
        this.jobpartmail = new JobPartMailAPI(client);
        this.jobpartoption = new JobPartOptionAPI(client);
        this.jobpartoutsidepurch = new JobPartOutsidePurchAPI(client);
        this.jobpartprepressop = new JobPartPrePressOpAPI(client);
        this.jobpartpressform = new JobPartPressFormAPI(client);
        this.jobpartpressformcontent = new JobPartPressFormContentAPI(client);
        this.jobpartpressformevent = new JobPartPressFormEventAPI(client);
        this.jobpartpressformink = new JobPartPressFormInkAPI(client);
        this.jobpartpressformmixedmedia = new JobPartPressFormMixedMediaAPI(client);
        this.jobpartsalesdist = new JobPartSalesDistAPI(client);
        this.jobpartsalesdistline = new JobPartSalesDistLineAPI(client);
        this.jobpartsizeallowance = new JobPartSizeAllowanceAPI(client);
        this.jobplan = new JobPlanAPI(client);
        this.jobplandependancies = new JobPlanDependanciesAPI(client);
        this.jobplanlink = new JobPlanLinkAPI(client);
        this.jobplansetup = new JobPlanSetupAPI(client);
        this.jobproduct = new JobProductAPI(client);
        this.jobproducttype = new JobProductTypeAPI(client);
        this.jobproject = new JobProjectAPI(client);
        this.jobreorder = new JobReorderAPI(client);
        this.jobshipment = new JobShipmentAPI(client);
        this.jobstatus = new JobStatusAPI(client);
        this.jobstatusreason = new JobStatusReasonAPI(client);
        this.jobtracking = new JobTrackingAPI(client);
        this.jobtype = new JobTypeAPI(client);
        this.jobtypeplan = new JobTypePlanAPI(client);
        this.joinedgroup = new JoinedGroupAPI(client);
        this.keypad = new KeypadAPI(client);
        this.language = new LanguageAPI(client);
        this.languageregion = new LanguageRegionAPI(client);
        this.legalentity = new LegalEntityAPI(client);
        this.link = new LinkAPI(client);
        this.listsource = new ListSourceAPI(client);
        this.localfileattachment = new LocalFileAttachmentAPI(client);
        this.lookandfeel = new LookAndFeelAPI(client);
        this.lot = new LotAPI(client);
        this.lotcyclecount = new LotCycleCountAPI(client);
        this.mailingclass = new MailingClassAPI(client);
        this.mailingsetup = new MailingSetupAPI(client);
        this.mailingsize = new MailingSizeAPI(client);
        this.mailingtabs = new MailingTabsAPI(client);
        this.mailingtype = new MailingTypeAPI(client);
        this.manufacturinglocation = new ManufacturingLocationAPI(client);
        this.manufacturinglocationshipdatetime = new ManufacturingLocationShipDateTimeAPI(client);
        this.masterbilloflading = new MasterBillOfLadingAPI(client);
        this.materialprovided = new MaterialProvidedAPI(client);
        this.merchantaccount = new MerchantAccountAPI(client);
        this.metrixcutteroperation = new MetrixCutterOperationAPI(client);
        this.metrixexportprofile = new MetrixExportProfileAPI(client);
        this.metrixfinishinggroup = new MetrixFinishingGroupAPI(client);
        this.metrixfoldpattern = new MetrixFoldPatternAPI(client);
        this.metroarearelay = new MetroAreaRelayAPI(client);
        this.metropolitanarea = new MetropolitanAreaAPI(client);
        this.networklocation = new NetworkLocationAPI(client);
        this.nonchargeabletime = new NonChargeableTimeAPI(client);
        this.nonchargeabletype = new NonChargeableTypeAPI(client);
        this.nonplannedreason = new NonPlannedReasonAPI(client);
        this.notecategory = new NoteCategoryAPI(client);
        this.notification = new NotificationAPI(client);
        this.notificationread = new NotificationReadAPI(client);
        this.notificationrecipient = new NotificationRecipientAPI(client);
        this.notificationsetup = new NotificationSetupAPI(client);
        this.objectcontextfilterrelationtype = new ObjectContextFilterRelationTypeAPI(client);
        this.objectcontextfiltertype = new ObjectContextFilterTypeAPI(client);
        this.objectcontextsecurityfilter = new ObjectContextSecurityFilterAPI(client);
        this.opportunity = new OpportunityAPI(client);
        this.opportunitytype = new OpportunityTypeAPI(client);
        this.option = new OptionAPI(client);
        this.optionlist = new OptionListAPI(client);
        this.organization = new OrganizationAPI(client);
        this.organizationcompany = new OrganizationCompanyAPI(client);
        this.organizationsystemuser = new OrganizationSystemUserAPI(client);
        this.organizationsystemusercompany = new OrganizationSystemUserCompanyAPI(client);
        this.outsidepurchasedescriptiontemplate = new OutsidePurchaseDescriptionTemplateAPI(client);
        this.outsidepurchasetemplate = new OutsidePurchaseTemplateAPI(client);
        this.outsidepurchasevendorprice = new OutsidePurchaseVendorPriceAPI(client);
        this.outsidepurchaseworkflow = new OutsidePurchaseWorkflowAPI(client);
        this.outsidepurchaseworkflowitem = new OutsidePurchaseWorkflowItemAPI(client);
        this.posetup = new POSetupAPI(client);
        this.postatus = new POStatusAPI(client);
        this.paceconnect = new PaceConnectAPI(client);
        this.paceconnectcomment = new PaceConnectCommentAPI(client);
        this.paceconnectdatabaseconnection = new PaceConnectDatabaseConnectionAPI(client);
        this.paceconnectevent = new PaceConnectEventAPI(client);
        this.paceconnectexpression = new PaceConnectExpressionAPI(client);
        this.paceconnectexpressionmap = new PaceConnectExpressionMapAPI(client);
        this.paceconnectexternalexpression = new PaceConnectExternalExpressionAPI(client);
        this.paceconnectfailedoutput = new PaceConnectFailedOutputAPI(client);
        this.paceconnectfieldmigration = new PaceConnectFieldMigrationAPI(client);
        this.paceconnectfile = new PaceConnectFileAPI(client);
        this.paceconnectheader = new PaceConnectHeaderAPI(client);
        this.paceconnectjmfmessagetype = new PaceConnectJMFMessageTypeAPI(client);
        this.paceconnectjmfqueueentry = new PaceConnectJMFQueueEntryAPI(client);
        this.paceconnectlocation = new PaceConnectLocationAPI(client);
        this.paceconnectmap = new PaceConnectMapAPI(client);
        this.paceconnectmapconfig = new PaceConnectMapConfigAPI(client);
        this.paceconnectmapconfigentry = new PaceConnectMapConfigEntryAPI(client);
        this.paceconnectobjectmigration = new PaceConnectObjectMigrationAPI(client);
        this.paceconnectpendingfile = new PaceConnectPendingFileAPI(client);
        this.paceconnectpendingfileparameter = new PaceConnectPendingFileParameterAPI(client);
        this.paceconnectresult = new PaceConnectResultAPI(client);
        this.paceconnectsizemap = new PaceConnectSizeMapAPI(client);
        this.paceconnectsync = new PaceConnectSyncAPI(client);
        this.pacequotesetup = new PaceQuoteSetupAPI(client);
        this.padding = new PaddingAPI(client);
        this.papercost = new PaperCostAPI(client);
        this.papersize = new PaperSizeAPI(client);
        this.papersizeinventory = new PaperSizeInventoryAPI(client);
        this.papertype = new PaperTypeAPI(client);
        this.papertypeactivity = new PaperTypeActivityAPI(client);
        this.paperweight = new PaperWeightAPI(client);
        this.patterncategory = new PatternCategoryAPI(client);
        this.patternsizeallowance = new PatternSizeAllowanceAPI(client);
        this.payment = new PaymentAPI(client);
        this.paymentbatch = new PaymentBatchAPI(client);
        this.paymentline = new PaymentLineAPI(client);
        this.paymentmethod = new PaymentMethodAPI(client);
        this.payrollbatch = new PayrollBatchAPI(client);
        this.payrollcheck = new PayrollCheckAPI(client);
        this.payrollcheckline = new PayrollCheckLineAPI(client);
        this.payrollchecktype = new PayrollCheckTypeAPI(client);
        this.payrolldeductiontype = new PayrollDeductionTypeAPI(client);
        this.payrollpaytype = new PayrollPayTypeAPI(client);
        this.payrollpaytypeexcludededuction = new PayrollPayTypeExcludeDeductionAPI(client);
        this.payrollsetup = new PayrollSetupAPI(client);
        this.payrolltaxtable = new PayrollTaxTableAPI(client);
        this.payrolltaxtableline = new PayrollTaxTableLineAPI(client);
        this.permission = new PermissionAPI(client);
        this.permitbilling = new PermitBillingAPI(client);
        this.permitprint = new PermitPrintAPI(client);
        this.permitused = new PermitUsedAPI(client);
        this.persistentqueue = new PersistentQueueAPI(client);
        this.plate = new PlateAPI(client);
        this.postagetype = new PostageTypeAPI(client);
        this.prepactivity = new PrepActivityAPI(client);
        this.prepmethod = new PrepMethodAPI(client);
        this.prepresscost = new PrepressCostAPI(client);
        this.prepressitem = new PrepressItemAPI(client);
        this.prepressitemgroup = new PrepressItemGroupAPI(client);
        this.prepresssize = new PrepressSizeAPI(client);
        this.prepressworkflow = new PrepressWorkflowAPI(client);
        this.press = new PressAPI(client);
        this.pressconsolebutton = new PressConsoleButtonAPI(client);
        this.presscutoff = new PressCutoffAPI(client);
        this.pressevent = new PressEventAPI(client);
        this.presseventruncostbasis = new PressEventRunCostBasisAPI(client);
        this.presseventworkflow = new PressEventWorkflowAPI(client);
        this.presseventworkflowitem = new PressEventWorkflowItemAPI(client);
        this.pressfeeddirection = new PressFeedDirectionAPI(client);
        this.pressinktype = new PressInkTypeAPI(client);
        this.pressspeed = new PressSpeedAPI(client);
        this.presstype = new PressTypeAPI(client);
        this.presstypeinktype = new PressTypeInkTypeAPI(client);
        this.presstypespeedmethod = new PressTypeSpeedMethodAPI(client);
        this.previouspassword = new PreviousPasswordAPI(client);
        this.price = new PriceAPI(client);
        this.pricedetail = new PriceDetailAPI(client);
        this.pricelist = new PriceListAPI(client);
        this.pricelistline = new PriceListLineAPI(client);
        this.printcase = new PrintCaseAPI(client);
        this.printrunmethod = new PrintRunMethodAPI(client);
        this.printservice = new PrintServiceAPI(client);
        this.printtype = new PrintTypeAPI(client);
        this.printer = new PrinterAPI(client);
        this.printerpapermapping = new PrinterPaperMappingAPI(client);
        this.printersettings = new PrinterSettingsAPI(client);
        this.printstreambatch = new PrintstreamBatchAPI(client);
        this.printstreamlot = new PrintstreamLotAPI(client);
        this.priority = new PriorityAPI(client);
        this.product = new ProductAPI(client);
        this.productexpression = new ProductExpressionAPI(client);
        this.productgroup = new ProductGroupAPI(client);
        this.productitem = new ProductItemAPI(client);
        this.productorder = new ProductOrderAPI(client);
        this.productprice = new ProductPriceAPI(client);
        this.productquantity = new ProductQuantityAPI(client);
        this.producttemplate = new ProductTemplateAPI(client);
        this.producttype = new ProductTypeAPI(client);
        this.productiontype = new ProductionTypeAPI(client);
        this.proof = new ProofAPI(client);
        this.purchaseorder = new PurchaseOrderAPI(client);
        this.purchaseorderline = new PurchaseOrderLineAPI(client);
        this.purchaseorderlineshipto = new PurchaseOrderLineShipToAPI(client);
        this.purchaseorderreceipt = new PurchaseOrderReceiptAPI(client);
        this.purchaseordertype = new PurchaseOrderTypeAPI(client);
        this.purchasingauthorization = new PurchasingAuthorizationAPI(client);
        this.quantity = new QuantityAPI(client);
        this.quantitylabel = new QuantityLabelAPI(client);
        this.quantitypricediscount = new QuantityPriceDiscountAPI(client);
        this.question = new QuestionAPI(client);
        this.questionnairepart = new QuestionnairePartAPI(client);
        this.questionnaireproduct = new QuestionnaireProductAPI(client);
        this.questionnaireresponse = new QuestionnaireResponseAPI(client);
        this.questionnairestatus = new QuestionnaireStatusAPI(client);
        this.questionnairetopic = new QuestionnaireTopicAPI(client);
        this.questionnairetype = new QuestionnaireTypeAPI(client);
        this.queuednotification = new QueuedNotificationAPI(client);
        this.quote = new QuoteAPI(client);
        this.quotecalcmessage = new QuoteCalcMessageAPI(client);
        this.quotecategory = new QuoteCategoryAPI(client);
        this.quotecategorygroup = new QuoteCategoryGroupAPI(client);
        this.quotecomponent = new QuoteComponentAPI(client);
        this.quotedepartment = new QuoteDepartmentAPI(client);
        this.quoteexpression = new QuoteExpressionAPI(client);
        this.quoteitem = new QuoteItemAPI(client);
        this.quoteitemprice = new QuoteItemPriceAPI(client);
        this.quoteitemtype = new QuoteItemTypeAPI(client);
        this.quoteitemtypeactivitycode = new QuoteItemTypeActivityCodeAPI(client);
        this.quoteitemtypeinventoryitem = new QuoteItemTypeInventoryItemAPI(client);
        this.quoteitemtypeprintservice = new QuoteItemTypePrintServiceAPI(client);
        this.quoteitemtypeudf = new QuoteItemTypeUdfAPI(client);
        this.quoteletter = new QuoteLetterAPI(client);
        this.quoteletternote = new QuoteLetterNoteAPI(client);
        this.quotelettertext = new QuoteLetterTextAPI(client);
        this.quotelettertype = new QuoteLetterTypeAPI(client);
        this.quotelettertypetext = new QuoteLetterTypeTextAPI(client);
        this.quotenote = new QuoteNoteAPI(client);
        this.quoteprice = new QuotePriceAPI(client);
        this.quoteproduct = new QuoteProductAPI(client);
        this.quoteproductcontentfile = new QuoteProductContentFileAPI(client);
        this.quotequantity = new QuoteQuantityAPI(client);
        this.quoteshipment = new QuoteShipmentAPI(client);
        this.rsschannel = new RSSChannelAPI(client);
        this.ratelevel = new RateLevelAPI(client);
        this.receivable = new ReceivableAPI(client);
        this.receivableline = new ReceivableLineAPI(client);
        this.receivablepaymentgroup = new ReceivablePaymentGroupAPI(client);
        this.receivablepaymentgroupline = new ReceivablePaymentGroupLineAPI(client);
        this.recentitem = new RecentItemAPI(client);
        this.recurrence = new RecurrenceAPI(client);
        this.relatedinventoryitems = new RelatedInventoryItemsAPI(client);
        this.relaydatetime = new RelayDateTimeAPI(client);
        this.report = new ReportAPI(client);
        this.reportcategory = new ReportCategoryAPI(client);
        this.reportcondition = new ReportConditionAPI(client);
        this.reportemailrecipient = new ReportEmailRecipientAPI(client);
        this.reportfile = new ReportFileAPI(client);
        this.reportpackage = new ReportPackageAPI(client);
        this.reportpackageentry = new ReportPackageEntryAPI(client);
        this.reportpackageentryparameter = new ReportPackageEntryParameterAPI(client);
        this.reportpaper = new ReportPaperAPI(client);
        this.reportparameter = new ReportParameterAPI(client);
        this.reportprinter = new ReportPrinterAPI(client);
        this.reportsettings = new ReportSettingsAPI(client);
        this.reportversioncategory = new ReportVersionCategoryAPI(client);
        this.returnprint = new ReturnPrintAPI(client);
        this.revenuetype = new RevenueTypeAPI(client);
        this.revision = new RevisionAPI(client);
        this.router = new RouterAPI(client);
        this.routingtemplate = new RoutingTemplateAPI(client);
        this.routingtemplateorder = new RoutingTemplateOrderAPI(client);
        this.routingtemplateorderactivitycode = new RoutingTemplateOrderActivityCodeAPI(client);
        this.rushcharge = new RushChargeAPI(client);
        this.salescategory = new SalesCategoryAPI(client);
        this.salescategorytaxrate = new SalesCategoryTaxRateAPI(client);
        this.salesperson = new SalesPersonAPI(client);
        this.salesstage = new SalesStageAPI(client);
        this.salestax = new SalesTaxAPI(client);
        this.salutation = new SalutationAPI(client);
        this.samples = new SamplesAPI(client);
        this.schedulestatus = new ScheduleStatusAPI(client);
        this.scheduledtask = new ScheduledTaskAPI(client);
        this.scheduledtaskemailrecipient = new ScheduledTaskEmailRecipientAPI(client);
        this.scheduledtasknotificationrecipient = new ScheduledTaskNotificationRecipientAPI(client);
        this.scheduledtaskoutputlocation = new ScheduledTaskOutputLocationAPI(client);
        this.scheduledtaskparameter = new ScheduledTaskParameterAPI(client);
        this.scheduledtaskresult = new ScheduledTaskResultAPI(client);
        this.schedulingflag = new SchedulingFlagAPI(client);
        this.securityfilter = new SecurityFilterAPI(client);
        this.securityfilteritem = new SecurityFilterItemAPI(client);
        this.securityfilterrelationtype = new SecurityFilterRelationTypeAPI(client);
        this.securityfiltertype = new SecurityFilterTypeAPI(client);
        this.shipprovider = new ShipProviderAPI(client);
        this.shipratesheetentry = new ShipRateSheetEntryAPI(client);
        this.shipvia = new ShipViaAPI(client);
        this.shipzone = new ShipZoneAPI(client);
        this.shipzonepostalcode = new ShipZonePostalCodeAPI(client);
        this.shipmentdistribution = new ShipmentDistributionAPI(client);
        this.shipmenttype = new ShipmentTypeAPI(client);
        this.shippingappsettings = new ShippingAppSettingsAPI(client);
        this.shippingworkflow = new ShippingWorkflowAPI(client);
        this.shippingworkflowfinishingop = new ShippingWorkflowFinishingOpAPI(client);
        this.shoppingcart = new ShoppingCartAPI(client);
        this.shoppingcartextra = new ShoppingCartExtraAPI(client);
        this.shoppingcartextratemplate = new ShoppingCartExtraTemplateAPI(client);
        this.size = new SizeAPI(client);
        this.sizeallowancetype = new SizeAllowanceTypeAPI(client);
        this.skid = new SkidAPI(client);
        this.sourcetype = new SourceTypeAPI(client);
        this.speedfactor = new SpeedFactorAPI(client);
        this.standardpapertype = new StandardPaperTypeAPI(client);
        this.state = new StateAPI(client);
        this.statustype = new StatusTypeAPI(client);
        this.subjobtype = new SubJobTypeAPI(client);
        this.subnotecategory = new SubNoteCategoryAPI(client);
        this.subproductgroup = new SubProductGroupAPI(client);
        this.suggestedroll = new SuggestedRollAPI(client);
        this.systemgroup = new SystemGroupAPI(client);
        this.systemuser = new SystemUserAPI(client);
        this.tag = new TagAPI(client);
        this.tagcategory = new TagCategoryAPI(client);
        this.taxcategory = new TaxCategoryAPI(client);
        this.taxreport = new TaxReportAPI(client);
        this.taxreportcategory = new TaxReportCategoryAPI(client);
        this.taxreportmonth = new TaxReportMonthAPI(client);
        this.taxreportperiod = new TaxReportPeriodAPI(client);
        this.taxreportperiodcategory = new TaxReportPeriodCategoryAPI(client);
        this.taxreportperiodcategorysalestax = new TaxReportPeriodCategorySalesTaxAPI(client);
        this.taxreportperiodmonthmapping = new TaxReportPeriodMonthMappingAPI(client);
        this.taxablecode = new TaxableCodeAPI(client);
        this.terms = new TermsAPI(client);
        this.termsdiscount = new TermsDiscountAPI(client);
        this.threeknife = new ThreeKnifeAPI(client);
        this.topic = new TopicAPI(client);
        this.topicquestion = new TopicQuestionAPI(client);
        this.topicquestionresponsehandler = new TopicQuestionResponseHandlerAPI(client);
        this.twitteraccount = new TwitterAccountAPI(client);
        this.uom = new UOMAPI(client);
        this.uomdimension = new UOMDimensionAPI(client);
        this.uomrange = new UOMRangeAPI(client);
        this.uomsetup = new UOMSetupAPI(client);
        this.uomtype = new UOMTypeAPI(client);
        this.userdefinedcontext = new UserDefinedContextAPI(client);
        this.userdefinedform = new UserDefinedFormAPI(client);
        this.userdefinedformextractedobject = new UserDefinedFormExtractedObjectAPI(client);
        this.userdefinedformrequiredobject = new UserDefinedFormRequiredObjectAPI(client);
        this.userdefinedincludableform = new UserDefinedIncludableFormAPI(client);
        this.userdefinedinquiry = new UserDefinedInquiryAPI(client);
        this.userdefinedinquirycategory = new UserDefinedInquiryCategoryAPI(client);
        this.userdefinedinquirycontextmenuobject = new UserDefinedInquiryContextMenuObjectAPI(client);
        this.userdefinedinquiryrecipient = new UserDefinedInquiryRecipientAPI(client);
        this.userdefinedmenu = new UserDefinedMenuAPI(client);
        this.userdefinedmenuitem = new UserDefinedMenuItemAPI(client);
        this.userdefinedview = new UserDefinedViewAPI(client);
        this.userform = new UserFormAPI(client);
        this.userinterfaceset = new UserInterfaceSetAPI(client);
        this.velocitytemplate = new VelocityTemplateAPI(client);
        this.vendor = new VendorAPI(client);
        this.vendorcertification = new VendorCertificationAPI(client);
        this.vendornote = new VendorNoteAPI(client);
        this.vendorpaper = new VendorPaperAPI(client);
        this.vendorpaperprice = new VendorPaperPriceAPI(client);
        this.vendortype = new VendorTypeAPI(client);
        this.virtualprinter = new VirtualPrinterAPI(client);
        this.wipcategory = new WIPCategoryAPI(client);
        this.workstation = new WorkstationAPI(client);
        this.workstationactivitycode = new WorkstationActivityCodeAPI(client);
        this.workstationemployee = new WorkstationEmployeeAPI(client);
        this.workstationinventoryitem = new WorkstationInventoryItemAPI(client);
        this.workstationnonchargeabletype = new WorkstationNonChargeableTypeAPI(client);
        this.workstationnonplannedreason = new WorkstationNonPlannedReasonAPI(client);
        this.wrapstyle = new WrapStyleAPI(client);
    }
} 
